-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 10:56:56 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema STEPS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema STEPS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `STEPS` DEFAULT CHARACTER SET utf8 ;
USE `STEPS` ;

-- -----------------------------------------------------
-- Table `STEPS`.`administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STEPS`.`administrator` ;

CREATE TABLE IF NOT EXISTS `STEPS`.`administrator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STEPS`.`coach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STEPS`.`coach` ;

CREATE TABLE IF NOT EXISTS `STEPS`.`coach` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `team_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STEPS`.`guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STEPS`.`guest` ;

CREATE TABLE IF NOT EXISTS `STEPS`.`guest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STEPS`.`sport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STEPS`.`sport` ;

CREATE TABLE IF NOT EXISTS `STEPS`.`sport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `min_teams` INT NULL,
  `max_teams` INT NULL,
  `division_team` VARCHAR(45) NULL,
  `min_team_size` INT NULL,
  `max_team_size` INT NULL,
  `game_rules` VARCHAR(45) NULL,
  `is_indoor` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STEPS`.`division`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STEPS`.`division` ;

CREATE TABLE IF NOT EXISTS `STEPS`.`division` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `is_indoor` VARCHAR(45) NULL,
  `team_max` INT NULL,
  `player_max` INT NULL,
  `winning_team` VARCHAR(45) NULL,
  `season_end_date` VARCHAR(45) NULL,
  `sport_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_division_sport1_idx` (`sport_id` ASC),
  CONSTRAINT `fk_division_sport1`
    FOREIGN KEY (`sport_id`)
    REFERENCES `STEPS`.`sport` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STEPS`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STEPS`.`team` ;

CREATE TABLE IF NOT EXISTS `STEPS`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `player_count` VARCHAR(45) NULL,
  `active` INT NULL,
  `rank` INT NULL,
  `wins` INT NULL,
  `losses` INT NULL,
  `division_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_team_division1_idx` (`division_id` ASC),
  CONSTRAINT `fk_team_division1`
    FOREIGN KEY (`division_id`)
    REFERENCES `STEPS`.`division` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STEPS`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STEPS`.`player` ;

CREATE TABLE IF NOT EXISTS `STEPS`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_player_team1_idx` (`team_id` ASC),
  CONSTRAINT `fk_player_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `STEPS`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STEPS`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STEPS`.`user` ;

CREATE TABLE IF NOT EXISTS `STEPS`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `privileges` VARCHAR(45) NULL,
  `administrator_id` INT NULL,
  `coach_id` INT NULL,
  `guest_id` INT NULL,
  `player_id` INT NULL,
  PRIMARY KEY (`id`))

ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STEPS`.`tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STEPS`.`tournament` ;

CREATE TABLE IF NOT EXISTS `STEPS`.`tournament` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `begin_date` VARCHAR(45) NULL,
  `end_date` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `administrator_id` INT NOT NULL,
  `sport_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tournament_administrator1_idx` (`administrator_id` ASC),
  INDEX `fk_tournament_sport1_idx` (`sport_id` ASC),
  CONSTRAINT `fk_tournament_administrator1`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `STEPS`.`administrator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tournament_sport1`
    FOREIGN KEY (`sport_id`)
    REFERENCES `STEPS`.`sport` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STEPS`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STEPS`.`game` ;

CREATE TABLE IF NOT EXISTS `STEPS`.`game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `division_id` INT NULL,
  `team_1` VARCHAR(45) NULL,
  `team_2` VARCHAR(45) NULL,
  `venue` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `coach_1_score` INT NULL,
  `coach_2_score` INT NULL,
  `winner` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_game_team1_idx` (`team_id` ASC),
  CONSTRAINT `fk_game_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `STEPS`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STEPS`.`tournament_bracket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STEPS`.`tournament_bracket` ;

CREATE TABLE IF NOT EXISTS `STEPS`.`tournament_bracket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `round_id` VARCHAR(45) NOT NULL,
  `game_id` VARCHAR(45) NOT NULL,
  `venue` VARCHAR(45) NULL,
  `game_date` VARCHAR(45) NULL,
  `playoff_game_winner` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `winning_team_1` VARCHAR(45) NULL,
  `winning_team_2` VARCHAR(45) NULL,
  `tournament_id` INT NOT NULL,
  PRIMARY KEY (`id`, `round_id`, `game_id`),
  INDEX `fk_tournament_bracket_tournament1_idx` (`tournament_id` ASC),
  CONSTRAINT `fk_tournament_bracket_tournament1`
    FOREIGN KEY (`tournament_id`)
    REFERENCES `STEPS`.`tournament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
